[phases.setup]
nixPkgs = [
  'bun',
]

[phases.install]
cmds = [
  'bun install --frozen-lockfile'
]

[phases.build]
cmds = [
  'bun run turbo build --filter=my-v0-project'
]

[start]
cmd = 'cd apps/website && bun start' 