name: Deploy 

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
      coolify_url:
        required: true
        type: string
      coolify_app_uuid:
        required: true
        type: string
      coolify_token:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy to Coolify
        run: |
          curl -X PATCH \
            "${{ inputs.coolify_url }}/api/v1/applications/${{ inputs.coolify_app_uuid }}" \
            -H "Authorization: Bearer ${{ inputs.coolify_token }}" \
            -H "Content-Type: application/json" \
            -d '{
              "docker_registry_image_name": "${{ inputs.image_name }}",
              "docker_registry_image_tag": "${{ inputs.image_tag }}"
            }'
          
          curl -X GET \
            "${{ inputs.coolify_url }}/api/v1/deploy?uuid=${{ inputs.coolify_app_uuid }}" \
            -H "Authorization: Bearer ${{ inputs.coolify_token }}" \
            -H "Content-Type: application/json"
