name: Main Branch Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-core:
    name: Build Core Application
    uses: ./.github/workflows/build-core.yml
    with:
      registry: docker.io
      image_name: mlnative/paperjet-dev
    secrets: inherit
