name: Main Branch Build & Deploy

permissions:
  packages: write
  id-token: write
  contents: write
on:
  push:
    branches:
      - main

jobs:
  lint-typecheck:
    uses: ./.github/workflows/lint-typecheck.yml

  release:
    name: Semantic Release
    needs: lint-typecheck
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.release.outputs.new_release_version }}
      new_release_published: ${{ steps.release.outputs.new_release_published }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22 

      - name: Install dependencies
        run: bun install

      - name: Semantic release
        id: release
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-core:
    needs: release
    uses: ./.github/workflows/build-core.yml
    with:
      registry: docker.io
      image_name: mlnative/paperjet
      image_tag: ${{ needs.release.outputs.new_release_version }}
    secrets: inherit

  build-ml:
    needs: release
    uses: ./.github/workflows/build-ml.yml
    with:
      registry: docker.io
      image_name: mlnative/paperjet-ml
      image_tag: ${{ needs.release.outputs.new_release_version }}
    secrets: inherit

  deploy-core:
    name: Deploy Core to Production
    needs: [build-core, release]
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      registry: docker.io
      image_name: mlnative/paperjet
      image_tag: ${{ needs.release.outputs.new_release_version }}
      environment: production
    secrets:
      coolify_url: ${{ secrets.COOLIFY_PROD_URL }}
      coolify_app_uuid: ${{ secrets.COOLIFY_PROD_APP_UUID }}
      coolify_token: ${{ secrets.COOLIFY_PROD_TOKEN }}

  deploy-ml:
    name: Deploy ML to Production
    needs: [build-ml, release]
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      registry: docker.io
      image_name: mlnative/paperjet-ml
      image_tag: ${{ needs.release.outputs.new_release_version }}
      environment: production
    secrets:
      coolify_url: ${{ secrets.COOLIFY_PROD_URL }}
      coolify_app_uuid: ${{ secrets.COOLIFY_PROD_ML_APP_UUID }}
      coolify_token: ${{ secrets.COOLIFY_PROD_TOKEN }}
